### ISSUE TITLE
Correct the license (MIT, not SQLite)

### ISSUE THREAD

**Issue by a-teammate** [SamuelMarks/conan-rapidjson#2]
We are using `conan info --only=license` to get a list of all deps with their licenses for distribution.

However: Rapidjson is using the MIT License, not SQLite, could you fix that?

**Comment by SamuelMarks** [comment]
Oh, I thought that was the license for my install scripts. Will amend when I get to a computer.

**Comment by a-teammate** [comment]
Ah okay :D Thanks :)

**Comment by SamuelMarks** [comment]
Fixed
